# Site
repository: dbejanishvili/dbejanishvili.github.io
favicon: images/favicon.ico

# Personal info
name: David Bezhanishvili
title: Software Developer
email: datobejanishvili@gmail.com

# Social links
github_username:  dbejanishvili
stackoverflow_username: "1724663"
linkedin_username: davit-bezhanishvili
facebook_username: dato.bejanishvili.1
instagram_username: datobejanishvili

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# Achievements Section
achievements_title: Achievements

# More Section

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
