# Site
repository: dbejanishvili/dbejanishvili.github.io
favicon: images/favicon.ico

# Content configuration version
version: 1

# Personal info
name: David Bezhanishvili
title: Software Developer
email: datobejanishvili@gmail.com

# Social links
github_username:  dbejanishvili
stackoverflow_username: "1724663"
linkedin_username: davit-bezhanishvili
facebook_username: dato.bejanishvili.1

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is David and I'm a Software developer. I mainly work on desktop applications, but I've also had a lot of experience writing websites, web scrapping applications, DAPPs, machine learning models and so on. 
  Over the years I've been working on programming tasks of a wide variety. I've been learning algorithms for 8 years and teaching them for 4, in the process I have learned how to write quality code with minimal errors and optimal performance.
  I have been developing my problem-solving skills for over 8 years. I've participated in IMO(International Mathematical Olympiad) 2 times, have won the national Olympiad in math 3 times, have been awarded bronze and silver medals in IZhO ( International Zhautikov Olympiad).
  
# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# Achievements Section
achievements_title: Achievements

# More Section

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
