# Site
repository: dbejanishvili/dbejanishvili.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: David Bezhanishvili
title: Software Engineer
email: datobejanishvili@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  dbejanishvili
stackoverflow_username: "1724663"
linkedin_username: davit-bezhanishvili
facebook_username: dato.bejanishvili.1

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's David and I'm a Software developer. I mainly work on desktop applications, but I've also had a lot of experience writing websites, web scrapping applications, DAPPs, machine learning models and so on. 
  Over the years I've been working on programming tasks of a wide variety. I've been learning algorithms for 8 years and teaching them for 4, in the process I have learned how to write quality code with minimal errors and optimal performance.
  I have been developing my problem-solving skills for over 8 years. I've participated in IMO(International Mathematical Olympiad) 2 times, have won national Olympiad in math 3 times, have been awarded bronze and silver medals in IZhO ( International Zhautikov Olympiad).
  
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        name: E2E encryption plugin for Mattermost
        link: github.com/bakurits/mattermost-plugin-anonymous
        github: bakurits/mattermost-plugin-anonymous
        description: | # this will include new lines to allow paragraphs
          I started this project as a University Open-Source course assignment. It was a great opportunity to get to know a new language, and open source programming in general. The project provided end-to-end encryption for mattermost messaging platform and was well received by mattermost community.

      - layout: top-middle
        name: Splunk plugin for Mattermost
        description: | # this will include new lines to allow paragraphs
          This project was continuation of end-to-end encryption plugin for mattermost. It started as a bounty program hosted by mattermost team and provided a plugin that integrated splunk platform functionality into mattermost.

      - layout: top-middle
        name: MPLib
        link: github.com/OP-Solutions/MPLib
        github: OP-Solutions/MPLib
        description: | # this will include new lines to allow paragraphs
          MPLib (Mental Poker Library) is open source decentralized gambling library written in c# (.Netstandard 2).Main feature of this library is decentralized structure. The game process is completely serverless, clients are connected directly to each other and communicating without trusted 3rd party. This project is currently under development.
        
      - layout: top-middle
        name: Mavis
        link: github.com/OP-Solutions/Mavis-IOS-SDK
        github: OP-Solutions/Mavis-IOS-SDK
        description: | # this will include new lines to allow paragraphs
          Mavis SDK is a library that makes it possible to add AR experiences to existing Android/IOS applications. That is, it can recognize objects in camera view (real-time) by analyzing pre-defined images (for instance, credit card visuals). Upon recognizing an image Mavis draws various 3D and 2D objects around it.


      - layout: top-middle
        name: Gepherrini
        link: gepherrini.com
        description: | # this will include new lines to allow paragraphs
          Gepherrini is an online shop written by georgian software company "connect". Taking on this project was an opportunity to try out a new programming language and also get some experience in server management

      - layout: top-middle
        name: Tbilisi World Book Capital
        link: twbc.ge
        description: | # this will include new lines to allow paragraphs
          World Book Capital is a project of the United Nations Education, Scientific and Cultural Organization (UNESCO). Since April 23, 2021, Tbilisi has assumed this honorable status for exactly one year. Twbc.ge is a website for said event. Taking on this project was very interesting, considering i had to learn working with a new framework, also it was a good practice in already familiar frameworks such as React.

      - layout: top-middle
        name: Decentralized Election Website
        link: github.com/bakurits/Election
        github: bakurits/Election
        description: | # this will include new lines to allow paragraphs
          This project was a part of my 2018-19 internship training at Birtvi, a georgian software company focused on building projects on Blockchain. It was a simple election website based on Etherium platform.

      - layout: top-middle
        name: ProChess
        link: github.com/Rogavactive/ProChess
        github: Rogavactive/ProChess
        description: | # this will include new lines to allow paragraphs
          A simple chess platform written as a part of a final project for OOP course in university.


      - layout: top-middle
        name: Imagine
        description: | # this will include new lines to allow paragraphs
          "Imagine" is a marketing platform that provides real time demographic evaluation of surrounding audience and optimises advertisements based on public present. It also provides statistics around each location and lets companies construct different campaigns around advertisements. This platform is still in development.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        company: OP Solutions Georgia
        link: linkedin.com/company/opsolutions-georgia/about/
        job_title: Co-founder & CEO
        dates: December 2019 – Present
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: top-middle
        company: Free University of Tbilisi
        link: http://www.freeuni.edu.ge/en
        jobs:   
          - title: Assistant to a lecturer in Programming Methodologies
            dates: September 2017 – February 2018
          - title: Seminar instructor in Programming Paradigms
            dates: September 2020 – Present
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: top-middle
        company: Birtvi
        link: linkedin.com/company/birtvi8/
        job_title: Intern Blockchain developer
        dates: November 2018 – January 2019
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: top-middle
        company: IT center MZIURI
        link: http://www.mziuri.ge/
        job_title: Teacher of a group in Olympic Informatics
        dates: January 2018 – July 2020
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: top-middle
        company: LEPL Tbilisi N42 Public School of Physics–Mathematics NamedAfter Academician Ilia Vekua
        link: vekua42.edu.ge/ge
        job_title: Teacher of a group in Olympic Mathematics
        dates: September 2016 - June 2019
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: top-middle
        company: Private Demirel College
        job_title: Teacher of a group in Olympic Mathematics
        dates: September 2016 – June 2017
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        name: Free University of Tbilisi
        dates: 2016 - 2020
        qualification: BSc in Maths and Computer Science
        description: | # this will include new lines to allow paragraphs
          During my time at Free University I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

      - layout: top-middle
        name: LEPL Tbilisi N42 Public School of Physics–Mathematics Named After Academician Ilia Vekua
        dates: 2011 - 2016
        qualification: High School diploma
        description: | # this will include new lines to allow paragraphs
          During my time at Free University I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        name: ACM-ICPC
        dates: 2016 - 2017
        achievement: Semifinalist
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
